### PR TITLE
rework About Us - Don't Merge!

### PR DESCRIPTION
**Pull request by thebearingedge**
@dogbot101 @dinhjeffrey @alexswiontek

I did a rewrite of the About Us section. Maybe we should keep suggested prep (install TeamViewer, git) in the README and break the tutorial parts into other files (but link to them). Nice work on the guides, BTW! Love the embedded pictures :tada: 

What do you guys think?

### CODE REVIEW

**Comment by thebearingedge** [comment]
Maybe a prep tutorial for installing Node too?

**Comment by thebearingedge** [comment]
Oh yeah. And if you are using sublime, [this package](https://github.com/revolunet/sublimetext-markdown-preview) is awesome for previewing your Github-Flavored Markdown!

**Comment by alexswiontek** [comment]
Nice work @thebearingedge , that looks much better. I second the Node install guide, maybe we can add a table of contents as the content we add to this readme starts to grow

**Comment by dinhjeffrey** [comment]
that sounds fine to me. if we break it into other files, would we create a readme2.md in the same repo and link it? 

Installing Node.js sounds good, I can work on that

**Comment by dinhjeffrey** [comment]
is it ok to merge now?

**Comment by alexswiontek** [comment]
@dinhjeffrey as far as a table of contents it could just be in the one README, and would just navigate throughout the document. Look at what they do for [Bootstrap](https://github.com/twbs/bootstrap)

**Comment by thebearingedge** [comment]
I'm ok with merging. Thanks!

**Pull request merged**
